package jbse.bc;

import java.util.Iterator;
import java.util.NoSuchElementException;

/**
 * Class representing a line number table.
 * 
 * @author Pietro Braione
 */
public final class LineNumberTable implements Iterable<LineNumberTable.Row> {
	/**
	 * Class representing a row in a line number table. A row
	 * represents the fact that, starting from a given program
	 * counter, the bytecodes have been generated by a given
	 * source code line with a given line number.
	 * 
	 * @author Pietro Braione
	 */
    public static final class Row {
        public final int start;
        public final int lineNumber;

        /**
         * Constructor.
         * 
         * @param start an {@code int}, the start program counter.  
         * @param lineNumber an {@code int}, the source code line number. 
         */
        Row(int start, int lineNumber) {
            this.start = start;
            this.lineNumber = lineNumber;
        }

        @Override
        public String toString() {
            return "<" + this.start + " " + this.lineNumber + ">";
        }
    }

    private final Row[] rows;
    private int next;

    public LineNumberTable(int rowsNumber) {
        this.rows = new Row[rowsNumber];
        this.next = 0;
    }

    public void addRow(int start, int lineNumber) {
        //silently rejects if out of range
        if (this.next >= this.rows.length) {
            return;
        }
        
        this.rows[this.next] = new Row(start, lineNumber);
        ++this.next;
    }

    @Override
    public Iterator<Row> iterator() {
        return new MyIterator();
    }

    private class MyIterator implements Iterator<Row> {
        int i = 0;

        public boolean hasNext() {
            return (i < LineNumberTable.this.rows.length && 
            LineNumberTable.this.rows[i] != null);
        }

        public Row next() {
            if (!hasNext()) {
                throw new NoSuchElementException();
            }
            ++i;
            return LineNumberTable.this.rows[i - 1];
        }

        public void remove() {
            throw new UnsupportedOperationException();
        }
    }
}

